import hashString from '@emotion/hash';

import { Core } from './types';
import { generateCss } from './generateCss';

export type UserOptions = {
  href?: string;
  precedence?: string;
};

type SeparatorPosition = {
  type: 'start' | 'end';
  separator: number;
  closingBrace: number;
};

type SeparatedCssItem = { type: 'regular' | 'separator'; content: string };

/**
 * Generated by Claude 3.5 Sonnet
 */
function findSeparatorPositions(text: string) {
  const startStr = '#__separator-start';
  const endStr = '#__separator-end';
  const positions: SeparatorPosition[] = [];
  let currentIndex = 0;

  while (true) {
    // Find next occurrence of either separator
    const startIndex = text.indexOf(startStr, currentIndex);
    const endIndex = text.indexOf(endStr, currentIndex);

    // If neither separator is found, we're done
    if (startIndex === -1 && endIndex === -1) break;

    // Determine which separator comes first (if both exist)
    let nextSeparator;
    let separatorType: SeparatorPosition['type'];
    if (startIndex === -1) {
      nextSeparator = endIndex;
      separatorType = 'end';
    } else if (endIndex === -1) {
      nextSeparator = startIndex;
      separatorType = 'start';
    } else {
      nextSeparator = Math.min(startIndex, endIndex);
      separatorType = nextSeparator === startIndex ? 'start' : 'end';
    }

    // Find next closing brace after the separator
    const searchFromIndex =
      nextSeparator +
      (separatorType === 'start' ? startStr.length : endStr.length);
    const braceIndex = text.indexOf('}', searchFromIndex);
    if (braceIndex === -1) break;

    // Store positions
    positions.push({
      type: separatorType,
      separator: nextSeparator,
      closingBrace: braceIndex,
    });

    // Move index to after the brace to find next occurrence
    currentIndex = braceIndex + 1;
  }

  return positions;
}

/**
 * Splits the string wherever a (--__breakpoint_query_placeholder__(name)) is found and
 * returns an interpolation to import breakpoint value at runtime.
 *
 * @example
 * ```js
 * const css = '@media (--__breakpoint_query_placeholder__xs) and (--__breakpoint_query_placeholder__lg) {}
 * ```
 *
 * becomes
 *
 * ```js
 * import { breakpoints } from 'import-to/config';
 *
 * const css = 'm
 */
function processRegularString(
  { types: t, addNamedImport }: Core,
  str: string
): ReturnType<
  Core['types']['templateLiteral'] | Core['types']['stringLiteral']
> {
  const regex = /(\(--__breakpoint_query_placeholder__(?<name>[a-z]+)\))/g;

  // Split the string by the pattern
  let result: (string | { breakpoint: string })[] = [];
  let lastIndex = 0;
  let match;

  // Use exec to iterate through all matches
  while ((match = regex.exec(str)) !== null) {
    // Add the text before the match
    if (match.index > lastIndex) {
      result.push(str.substring(lastIndex, match.index));
    }

    // Add the captured group (the breakpoint name)

    if (match.groups?.name) {
      result.push({
        breakpoint: match.groups.name,
      });
    }

    // Update lastIndex to continue after this match
    lastIndex = match.index + match[0].length;
  }

  // Add any remaining text after the last match
  if (lastIndex < str.length) {
    result.push(str.substring(lastIndex));
  }

  if (!result.length || result.length === 1) {
    return t.stringLiteral(str);
  }

  const templateElements: ReturnType<Core['types']['templateElement']>[] = [];
  const expressions: ReturnType<Core['types']['memberExpression']>[] = [];

  result.forEach((item) => {
    if (typeof item === 'string') {
      templateElements.push(t.templateElement({ raw: item }));
      return;
    }
    const breakpointsImport = addNamedImport('breakpoints');
    expressions.push(
      t.memberExpression(
        breakpointsImport,
        t.stringLiteral(item.breakpoint),
        true
      )
    );
  });

  return t.templateLiteral(templateElements, expressions);
}

function processBreakpointString(
  babel: Core,
  str: string
): ReturnType<
  Core['types']['callExpression'] | Core['types']['stringLiteral']
> {
  const { types: t } = babel;
  const cssString = str.split('__breakpoint_placeholder__');
  const breakpointsImport = babel.addNamedImport('breakpoints');
  if (cssString.length === 1) {
    return t.stringLiteral(cssString[0]);
  }
  const breakpointValueId = t.identifier('value');
  const breakpointKeyId = t.identifier('key');
  const expressions: ReturnType<Core['types']['identifier']>[] = [];
  for (let i = 0; i < cssString.length - 1; i++) {
    expressions.push(breakpointKeyId);
  }
  const templateElement = t.templateLiteral(
    cssString.map((content) => t.templateElement({ raw: content })),
    expressions
  );

  return t.callExpression(
    t.memberExpression(
      t.callExpression(
        t.memberExpression(t.identifier('Object'), t.identifier('keys')),
        [breakpointsImport]
      ),
      t.identifier('reduce')
    ),
    [
      t.arrowFunctionExpression(
        [t.identifier('acc'), breakpointKeyId],
        t.blockStatement([
          t.variableDeclaration('const', [
            t.variableDeclarator(
              breakpointValueId,
              t.memberExpression(breakpointsImport, breakpointKeyId, true)
            ),
          ]),
          t.returnStatement(
            t.binaryExpression('+', t.identifier('acc'), templateElement)
          ),
        ])
      ),
      t.stringLiteral(str.replaceAll('.__breakpoint_placeholder__', '')),
    ]
  );
}

function concatenateStrings(babel: Core, items: SeparatedCssItem[]) {
  const { types: t } = babel;
  if (items.length === 0) {
    return t.stringLiteral('');
  }
  if (items.length === 1) {
    return t.stringLiteral(items[0].content);
  }

  return items.reduce(
    (acc, currentItem, index) => {
      if (index === 0) {
        return processRegularString(babel, currentItem.content);
      }
      if (currentItem.type === 'regular') {
        return t.binaryExpression(
          '+',
          acc,
          processRegularString(babel, currentItem.content)
        );
      }
      return t.binaryExpression(
        '+',
        acc,
        processBreakpointString(babel, currentItem.content)
      );
    },
    t.stringLiteral('') as
      | ReturnType<Core['types']['stringLiteral']>
      | ReturnType<Core['types']['templateLiteral']>
      | ReturnType<Core['types']['binaryExpression']>
  );
}

function generateCssWithoutSeparators(babel: Core, cssString: string) {
  const positions = findSeparatorPositions(cssString);
  if (positions.length === 0) return babel.types.stringLiteral(cssString);
  if (positions.length % 2 !== 0) {
    throw new Error(
      `Unbalanced separators. Please check the input/output css. ${cssString}`
    );
  }
  const separatedCss: SeparatedCssItem[] = [];
  let lastStartPosition: SeparatorPosition | null = null;

  separatedCss.push({
    type: 'regular',
    content: cssString.slice(0, positions[0].separator),
  });

  for (const { type, separator, closingBrace } of positions) {
    if (type === 'start') {
      lastStartPosition = { type, separator, closingBrace };
    }
    if (type === 'end') {
      if (!lastStartPosition) {
        throw new Error('Found separator end without a start');
      }
      separatedCss.push({
        type: 'separator',
        content: cssString.slice(lastStartPosition.closingBrace + 1, separator),
      });
      lastStartPosition = null;
    }
  }

  if (lastStartPosition) {
    throw new Error('Found separator start without an end.');
  }

  separatedCss.push({
    type: 'regular',
    content: cssString.slice(positions[positions.length - 1].closingBrace + 1),
  });

  return concatenateStrings(babel, separatedCss);
}

export function generateStyledNode(
  babel: Core,
  css: string,
  options: UserOptions | null,
  filename?: string
): ReturnType<Core['types']['jsxElement']> {
  const { types: t } = babel;
  const { href, precedence = 'mui-components' } = options ?? {};
  const transformedCss = generateCss(css, filename);
  const concatednatedStrings = generateCssWithoutSeparators(
    babel,
    transformedCss
  );
  const styleIdentifier = babel.addNamedStyleImport('Style');

  const hash = href || hashString(transformedCss);

  const styleOpening = t.jsxOpeningElement(
    t.jsxIdentifier(styleIdentifier.name),
    [
      t.jsxAttribute(t.jsxIdentifier('href'), t.stringLiteral(hash)),
      t.jsxAttribute(
        t.jsxIdentifier('precedence'),
        t.stringLiteral(precedence)
      ),
    ],
    false
  );
  const styleTag = t.jsxElement(
    styleOpening,
    t.jsxClosingElement(t.jsxIdentifier('style')),
    [t.jsxExpressionContainer(concatednatedStrings)]
  );
  return styleTag;
}
