import hashString from '@emotion/hash';

import { Core } from './types';
import { generateCss, PLACEHOLDERS, Position } from './generateCss';

export type UserOptions = {
  href?: string;
  precedence?: string;
};

type SeparatorPosition = {
  type: 'start' | 'end';
  separator: number;
  closingBrace: number;
};

type SeparatedCssItem = { type: 'regular' | 'separator'; content: string };

/**
 * Generated by Claude 3.5 Sonnet
 */
function findSeparatorPositions(text: string) {
  const positions: SeparatorPosition[] = [];
  let currentIndex = 0;

  while (true) {
    // Find next occurrence of either separator
    const startIndex = text.indexOf(PLACEHOLDERS.SEPARATOR_START, currentIndex);
    const endIndex = text.indexOf(PLACEHOLDERS.SEPARATOR_END, currentIndex);

    // If neither separator is found, we're done
    if (startIndex === -1 && endIndex === -1) break;

    // Determine which separator comes first (if both exist)
    let nextSeparator;
    let separatorType: SeparatorPosition['type'];
    if (startIndex === -1) {
      nextSeparator = endIndex;
      separatorType = 'end';
    } else if (endIndex === -1) {
      nextSeparator = startIndex;
      separatorType = 'start';
    } else {
      nextSeparator = Math.min(startIndex, endIndex);
      separatorType = nextSeparator === startIndex ? 'start' : 'end';
    }

    // Find next closing brace after the separator
    const searchFromIndex =
      nextSeparator +
      (separatorType === 'start'
        ? PLACEHOLDERS.SEPARATOR_START.length
        : PLACEHOLDERS.SEPARATOR_END.length);
    const braceIndex = text.indexOf('}', searchFromIndex);
    if (braceIndex === -1) break;

    // Store positions
    positions.push({
      type: separatorType,
      separator: nextSeparator,
      closingBrace: braceIndex,
    });

    // Move index to after the brace to find next occurrence
    currentIndex = braceIndex + 1;
  }

  return positions;
}

/**
 * Splits the string wherever a (--__breakpoint_query_placeholder__(name)) is found and
 * returns an interpolation to import breakpoint value at runtime.
 *
 * @example
 * ```js
 * const css = '@media (--__breakpoint_query_placeholder__xs) and (--__breakpoint_query_placeholder__lg) {}
 * ```
 *
 * becomes
 *
 * ```js
 * import { breakpoints } from 'import-to/config';
 *
 * const css = `@media ${breakpoints['xs']} and ${breakpoints['lg']} {}`;
 * ```
 */
function processRegularString(
  { types: t, addNamedImport }: Core,
  str: string
): ReturnType<
  Core['types']['templateLiteral'] | Core['types']['stringLiteral']
> {
  const regex = /(\(--__breakpoint_query_placeholder__(?<name>[a-z]+)\))/g;

  // Split the string by the pattern
  let result: (string | { breakpoint: string })[] = [];
  let lastIndex = 0;
  let match;

  // Use exec to iterate through all matches
  while ((match = regex.exec(str)) !== null) {
    // Add the text before the match
    if (match.index > lastIndex) {
      result.push(str.substring(lastIndex, match.index));
    }

    // Add the captured group (the breakpoint name)

    if (match.groups?.name) {
      result.push({
        breakpoint: match.groups.name,
      });
    }

    // Update lastIndex to continue after this match
    lastIndex = match.index + match[0].length;
  }

  // Add any remaining text after the last match
  if (lastIndex < str.length) {
    result.push(str.substring(lastIndex));
  }

  if (!result.length || result.length === 1) {
    return t.stringLiteral(str);
  }

  const templateElements: ReturnType<Core['types']['templateElement']>[] = [];
  const expressions: ReturnType<Core['types']['memberExpression']>[] = [];

  result.forEach((item) => {
    if (typeof item === 'string') {
      templateElements.push(t.templateElement({ raw: item }));
      return;
    }
    const breakpointsImport = addNamedImport('breakpoints');
    expressions.push(
      t.memberExpression(
        breakpointsImport,
        t.stringLiteral(item.breakpoint),
        true
      )
    );
  });

  return t.templateLiteral(templateElements, expressions);
}

function processBreakpointString(
  babel: Core,
  str: string
): ReturnType<
  Core['types']['stringLiteral'] | Core['types']['callExpression']
> {
  const { types: t } = babel;
  let cssString = str.split(PLACEHOLDERS.BREAKPOINT_PLACEHOLDER);
  const breakpointsImport = babel.addNamedImport('breakpoints');
  if (cssString.length === 1) {
    return t.stringLiteral(cssString[0]);
  }
  const breakpointKeyId = t.identifier('key');
  const breakpointWithSlash = t.identifier('ks');
  const expressions: ReturnType<
    Core['types']['memberExpression' | 'identifier']
  >[] = [t.memberExpression(breakpointsImport, breakpointKeyId, true)];

  for (let i = 0; i < cssString.length - 1; i++) {
    expressions.push(breakpointWithSlash);
  }
  cssString = cssString.map((str, index) => {
    if (index === 0) {
      return `{ ${str}`;
    }
    if (index === cssString.length - 1) {
      return `${str} }`;
    }
    return str;
  });
  const templateElement = t.templateLiteral(
    ['@media ', ...cssString].map((content) =>
      t.templateElement({ raw: content })
    ),
    expressions
  );

  /**
   * Maybe we can generate a more optimized code.
   */
  return t.callExpression(
    t.memberExpression(
      t.callExpression(
        t.memberExpression(t.identifier('Object'), t.identifier('keys')),
        [breakpointsImport]
      ),
      t.identifier('reduce')
    ),
    [
      t.arrowFunctionExpression(
        [t.identifier('acc'), breakpointKeyId],
        t.blockStatement([
          t.variableDeclaration('const', [
            t.variableDeclarator(
              breakpointWithSlash,
              t.binaryExpression('+', breakpointKeyId, t.stringLiteral('\\'))
            ),
          ]),
          t.returnStatement(
            t.binaryExpression('+', t.identifier('acc'), templateElement)
          ),
        ])
      ),
      t.stringLiteral(
        str.replaceAll(`${PLACEHOLDERS.BREAKPOINT_PLACEHOLDER}\\:`, '')
      ),
    ]
  );
}

function concatenateStrings(babel: Core, items: SeparatedCssItem[]) {
  const { types: t } = babel;
  if (items.length === 0) {
    return t.stringLiteral('');
  }
  if (items.length === 1) {
    return t.stringLiteral(items[0].content);
  }

  return items.reduce(
    (acc, currentItem, index) => {
      if (index === 0) {
        return processRegularString(babel, currentItem.content);
      }
      if (currentItem.type === 'regular') {
        return t.binaryExpression(
          '+',
          acc,
          processRegularString(babel, currentItem.content)
        );
      }
      return t.binaryExpression(
        '+',
        acc,
        processBreakpointString(babel, currentItem.content)
      );
    },
    t.stringLiteral('') as
      | ReturnType<Core['types']['stringLiteral']>
      | ReturnType<Core['types']['templateLiteral']>
      | ReturnType<Core['types']['binaryExpression']>
  );
}

/**
 * Takes in the generated css with placeholders and generates an AST to support breakpoint concatenation at runtime.
 */
function generateCssWithoutSeparators(babel: Core, cssString: string) {
  const positions = findSeparatorPositions(cssString);
  if (positions.length === 0)
    return {
      hash: hashString(cssString),
      result: processRegularString(babel, cssString),
    };
  if (positions.length % 2 !== 0) {
    throw new Error(
      `Unbalanced separators. Please check the input/output css. ${cssString}`
    );
  }
  const separatedCss: SeparatedCssItem[] = [];
  let lastStartPosition: SeparatorPosition | null = null;
  let lastEndPostition: SeparatorPosition | null = null;

  separatedCss.push({
    type: 'regular',
    content: cssString.slice(0, positions[0].separator),
  });

  for (const position of positions) {
    if (position.type === 'start') {
      lastStartPosition = position;

      if (lastEndPostition) {
        separatedCss.push({
          type: 'regular',
          content: cssString.slice(
            lastEndPostition.closingBrace + 1,
            position.separator
          ),
        });
      }
    }
    if (position.type === 'end') {
      if (!lastStartPosition) {
        throw new Error('Found separator end without a start');
      }

      lastEndPostition = position;

      separatedCss.push({
        type: 'separator',
        content: cssString.slice(
          lastStartPosition.closingBrace + 1,
          position.separator
        ),
      });
      lastStartPosition = null;
    }
  }

  if (lastStartPosition) {
    throw new Error('Found separator start without an end.');
  }

  separatedCss.push({
    type: 'regular',
    content: cssString.slice(positions[positions.length - 1].closingBrace + 1),
  });

  const result = concatenateStrings(babel, separatedCss);
  const hash = hashString(separatedCss.map((s) => s.content).join(''));
  return {
    hash,
    result,
  };
}

/**
 * For the generated (transformed) css string, it generates an AST that supports breakpoints at runtime.
 */
export function generateStyledNode(
  babel: Core,
  css: string,
  options: UserOptions | null,
  filename?: string,
  location?: {
    start: Position;
    end: Position;
  } | null
): ReturnType<Core['types']['jsxElement']> {
  const { types: t } = babel;
  const { href, precedence = 'mui-components' } = options ?? {};
  const transformedCss = generateCss(css, filename, { location });
  const { hash: relevantHash, result: cssStringAST } =
    generateCssWithoutSeparators(babel, transformedCss);
  const styleIdentifier = babel.addNamedStyleImport('Style');

  const hash = href || relevantHash;
  const styleElement = t.jsxIdentifier(styleIdentifier.name);

  const styleOpening = t.jsxOpeningElement(
    styleElement,
    [
      t.jsxAttribute(t.jsxIdentifier('href'), t.stringLiteral(hash)),
      t.jsxAttribute(
        t.jsxIdentifier('precedence'),
        t.stringLiteral(precedence)
      ),
    ],
    false
  );
  const styleTag = t.jsxElement(
    styleOpening,
    t.jsxClosingElement(styleElement),
    [t.jsxExpressionContainer(cssStringAST)]
  );
  return styleTag;
}
